language: python
python:
    - "2.7"
    - "3.6"
install:
    - pip install -r requirements.txt
script: 
    - python -m pytest misc/test_code2.py -v --cov=code2 --cov-report=html
after_success:
    - coveralls
