language: python
python:
    - "3.6"
install:
    - pip install -r requirements.txt
    - pip install --only-binary=scipy scipy
    - pip install --only-binary=matplotlib matplotlib
script: 
    - python -m pytest tests/ -v --cov --cov-report=html
after_success:
    - coveralls
notifications:
    email: false
