language: python
python:
    - "2.7"
    - "3.6"
install:
    - pip install -r requirements.txt
script: 
    - python -m pytest src/laplace_solver.py -v --cov=laplace_solver --cov-report=html < sim_test.dat
after_success:
    - coveralls
notifications:
    email: false
